### ISSUE TITLE
See how many users are in voice channels

### ISSUE THREAD

**Issue by cronner** [kariudo/homeassistant-discord-bot#14]
Just got this working it's great :) so useful when playing games and need to move channel or mute.

Would be great with an entity to see in anyone has joined a voice channel

**Comment by kariudo** [comment]
Is the information you want not in the state of the "Users Online" already?

**Comment by cronner** [comment]
that's for online discord users not people that joined a voice channel right?

**Comment by kariudo** [comment]
@cronner I added `voiceChannel` as a property to the online users attribute, let me know if this works for you or if you needed more than this.
