### ISSUE TITLE
Use bot in multiple Servers

### ISSUE THREAD

**Issue by n8acl** [kariudo/homeassistant-discord-bot#15]
This is more of a question then an issue, but was not really sure where to put it.

I have the bot working and it is great. Has helped me with work flow and other things in one of my servers (family gaming server). 

I have multiple Discord servers that I "Own" (IE I am listed as the Server Owner on them). I would like to add this to another server of mine (one that is my "personal" one that I use for network notifications and other things that only I have access to) so that I can run automations with HA based on that server as well. 

Currently I have your bot running with Docker.

My question. How would home assistant list the different entities for the two servers and would it handle that? I know I would just setup another bot on the Dev Portal and would just spawn a new container in Docker for the new bot. I would also change the topic for MQTT to a unique one for this new bot. However, how would this be presented to HA? Would there be a naming conflict with the entities?

Thanks much!

**Comment by kariudo** [comment]
You just need to run a container for each server, and set a unique value for the env vars `TOPIC_BOT` where it will publish the status and `MQTT_CLIENT_ID` where it will advertise to Home Assistant.

Then they should just show up as separate device groupings with their respective sensors in HA.

Let me know if that doesn't work for you.
